Page({
	start:function(e){
		console.log('start',e)
	},
	move:function(e){
		console.log('move',e)
	},
	end:function(e){
		console.log('end',e)
	},
	canel:function(e){
		console.log('canel',e)
	},
	long:function(e){
		console.log('long',e)
	},
	error:function(e){
		console.log('error',e)
	}
})