Page({
	data:{
		beauty:10,
		whiteness:10
	},
	onReady:function(e){
		this.pusherContext = wx.createLivePusherContext();
	},
	schange:function(e){
		console.log(e.detail.value);
		this.setData({
			beauty:e.detail.value
		})
	},
	wchange:function(e){
		console.log(e.detail.value);
		this.setData({
			whiteness:e.detail.value
		})
	},
	change:function(e){
		console.log('change',e)
	},
	status:function(e){
		console.log('status',e)
	},
	error:function(e){
		console.log('error',e)
	},
	play:function(e){
		console.log('start',e)
		this.pusherContext.start({
			success:function(d){
				console.log('start-success',d)
			}
		});
	},
	pause:function(e){
		console.log('pause',e)
		this.pusherContext.pause({
			success:function(d){
				console.log('pause-success',d)
			}
		});
	},
	stop:function(e){
		console.log('stop',e)
		this.pusherContext.stop({
			success:function(d){
				console.log('stop-success',d)
			}
		});
	},
	snapshot:function(e){
		console.log('snapshot',e)
		this.pusherContext.snapshot({
			success:function(d){
				console.log('snapshot-success',d)
			}
		});
	},
	resume:function(e){
		console.log('resume',e)
		this.pusherContext.resume({
			success:function(d){
				console.log('resume-success',d)
			}
		});
	},
	camera:function(e){
		console.log('camera',e)
		this.pusherContext.switchCamera({
			success:function(d){
				console.log('camera-success',d)
			}
		});
	}
})