Page({
	showToast:function(e){
		console.log(e.currentTarget.dataset.type)
		if(e.currentTarget.dataset.type){
			wx.showToast({
				title:'标题',
				icon:e.currentTarget.dataset.type
			})
		}else{
			wx.showToast({
				title:'标题'
			})
		}

	},
	toastimg:function(e){
		wx.showToast({
			title:'标题',
			image:'../resources/kind/canvas.png'
		})
	},
	toastmask:function(e){
		wx.showToast({
			title:'标题',
			mask:true
		})
	},
	load:function(e){
		wx.showLoading({
			title:'标题'
		})
	},
	loadmask:function(e){
		wx.showLoading({
			title:'标题',
			mask:true,
			success:function(d){
				setTimeout(function(){
				  wx.hideLoading()
				},2000)
			}
		})
	},
	modal:function(e){
		console.log(e)
		wx.showModal({
			title:'标题',
			content:'提示的内容'
		})
	},
	modalcanel:function(e){
		console.log(e)
		wx.showModal({
			title:'标题',
			content:'提示的内容',
			showCancel:false,
			success:function(d){
				console.log(d)
				if(d.confirm){
					console.log('点击了确定')
				}
				if(d.cancel){
					console.log('点击了取消')
				}
			}
		})
	},
	modalcolor:function(e){
		console.log(e)
		wx.showModal({
			title:'标题',
			content:'提示的内容',
			cancelText:'取消1',
			cancelColor:'#0ff',
			confirmText:'确定1',
			confirmColor:'#f00',
			success:function(d){
				console.log(d)
				if(d.confirm){
					console.log('点击了确定')
				}
				if(d.cancel){
					console.log('点击了取消')
				}
			}
		})
	},
	action:function(e){
		console.log(e);
		wx.showActionSheet({
			itemList:['1','2','3'],
			itemColor:'#f00',
			success:function(d){
				console.log(d)
			}
		})
	}
})