Page({
	onReady:function(){
		this.playerContext = wx.createLivePlayerContext('player');
	},
	change:function(e){
		console.log('change',e.detail.code)
		if(e.detail.code==3005){
			this.exit();
		}
	},
	full:function(e){
		console.log('full',e)
	},
	status:function(e){
		console.log('status',e)
	},
	play:function(e){
		console.log('play',e)
		this.playerContext.play({
			success:function(d){
				console.log('play-success',d)
			}
		});
	},
	pause:function(e){
		console.log('pause',e)
		this.playerContext.pause({
			success:function(d){
				console.log('pause-success',d)
			}
		});
	},
	stop:function(e){
		console.log('stop',e)
		this.playerContext.stop({
			success:function(d){
				console.log('stop-success',d)
			}
		});
	},
	mute:function(e){
		console.log('mute',e)
		this.playerContext.mute({
			success:function(d){
				console.log('mute-success',d)
			}
		});
	},
	resume:function(e){
		console.log('resume',e)
		this.playerContext.resume({
			success:function(d){
				console.log('resume-success',d)
			}
		});
	},
	full:function(e){
		console.log('full',e)
		this.playerContext.requestFullScreen({
			success:function(d){
				console.log('full-success',d)
			}
		});
	},
	exit:function(e){
		console.log('exit',e)
		this.playerContext.exitFullScreen({
			success:function(d){
				console.log('exit-success',d)
			}
		});
	}
})